language: go

go:
  - "1.11"
  - "1.12"
  - master

install: true
env:
  - GO111MODULE=on

before_script:
  - go get golang.org/x/lint/golint

script:
  - go test -v -cover ./...
  - go vet ./...
  - golint -set_exit_status $(go list ./... | grep -v /vendor/)
